security:
  oauth2:
    client:
      clientId: <client-id>
      clientSecret: <client-secret>
      accessTokenUri: https://dev-133337.okta.com/oauth2/default/v1/token
      userAuthorizationUri: https://dev-133337.okta.com/oauth2/default/v1/authorize
      scope: openid profile email
    resource:
      userInfoUri: https://dev-133337.okta.com/oauth2/default/v1/userinfo
